export const verses = [
  "For God so loved the world… (John 3:16)",
  "The Lord is my shepherd… (Psalm 23:1)",
  "I can do all things through Christ… (Philippians 4:13)",
  "Trust in the Lord with all your heart… (Proverbs 3:5)",
  "Be strong and courageous… (Joshua 1:9)",
  "Rejoice always, pray continually… (1 Thessalonians 5:16-17)",
  "Love is patient, love is kind… (1 Corinthians 13:4-5)",
  "I will fear no evil… (Psalm 23:4)",
  "Your word is a lamp to my feet… (Psalm 119:105)",
  "Commit to the Lord whatever you do… (Proverbs 16:3)",
  "Cast all your anxiety on Him… (1 Peter 5:7)",
  "Blessed are the peacemakers… (Matthew 5:9)",
  "Delight yourself in the Lord… (Psalm 37:4)",
  "Do not be anxious about anything… (Philippians 4:6)",
  "Let your light shine before others… (Matthew 5:16)",
  "Create in me a clean heart… (Psalm 51:10)",
  "I am the way, the truth, and the life… (John 14:6)",
  "The Lord is my light and my salvation… (Psalm 27:1)",
  "My grace is sufficient for you… (2 Corinthians 12:9)",
  "Do everything in love… (1 Corinthians 16:14)",
  "The Lord will fight for you… (Exodus 14:14)",
  "Taste and see that the Lord is good… (Psalm 34:8)",
  "Blessed are those who hunger and thirst for righteousness… (Matthew 5:6)",
  "The Lord is near to all who call on Him… (Psalm 145:18)",
  "Faith can move mountains… (Matthew 17:20)",
  "Seek first the kingdom of God… (Matthew 6:33)",
  "The joy of the Lord is your strength… (Nehemiah 8:10)",
  "God is our refuge and strength… (Psalm 46:1)",
  "Peace I leave with you… (John 14:27)",
  "Be still and know that I am God… (Psalm 46:10)",
  "Walk in love… (Ephesians 5:2)",
  "Serve one another humbly… (Galatians 5:13)",
  "Let your hope make you glad… (Romans 12:12)",
  "Do not be overcome by evil… (Romans 12:21)",
  "A cheerful heart is good medicine… (Proverbs 17:22)",
  "The Lord is righteous in all His ways… (Psalm 145:17)",
  "You are the light of the world… (Matthew 5:14)",
  "Blessed is the one who trusts in the Lord… (Jeremiah 17:7)",
  "Cast your cares on the Lord… (Psalm 55:22)",
  "The Lord is compassionate and gracious… (Psalm 103:8)",
  "I will praise You, O Lord… (Psalm 146:1)",
  "Do not worry about tomorrow… (Matthew 6:34)",
  "Let everything that has breath praise the Lord… (Psalm 150:6)",
  "For I know the plans I have for you… (Jeremiah 29:11)",
  "The steadfast love of the Lord never ceases… (Lamentations 3:22)",
  "Taste and see that the Lord is good… (Psalm 34:8)",
  "The Lord is good, a stronghold in the day of trouble… (Nahum 1:7)",
  "Cast all your anxiety on Him… (1 Peter 5:7)",
  "The Lord is my strength and my shield… (Psalm 28:7)",
  "Blessed are the pure in heart… (Matthew 5:8)",
  "He heals the brokenhearted… (Psalm 147:3)",
  "Come to me, all who are weary… (Matthew 11:28)",
  "Let the peace of Christ rule in your hearts… (Colossians 3:15)",
  "Be strong and take heart… (Psalm 31:24)",
  "The Lord is gracious and compassionate… (Psalm 111:4)",
  "God is our refuge and strength… (Psalm 46:1)",
  "Rejoice in the Lord always… (Philippians 4:4)",
  "Trust in Him at all times… (Psalm 62:8)",
  "Be kind to one another… (Ephesians 4:32)",
  "Do not fear, for I am with you… (Isaiah 41:10)",
  "Love your neighbor as yourself… (Matthew 22:39)",
  "Bear one another's burdens… (Galatians 6:2)",
  "The Lord is my shepherd… (Psalm 23:1)",
  "Your word is a lamp to my feet… (Psalm 119:105)",
  "Be still and know that I am God… (Psalm 46:10)",
  "Commit your way to the Lord… (Psalm 37:5)",
  "The Lord is my rock and my fortress… (Psalm 18:2)",
  "I can do all things through Christ… (Philippians 4:13)",
  "Blessed are the merciful… (Matthew 5:7)",
  "Fear not, for I am with you… (Isaiah 43:5)",
  "God is love… (1 John 4:8)",
  "The Lord is my light and my salvation… (Psalm 27:1)",
  "Trust in the Lord and do good… (Psalm 37:3)",
  "Do not be afraid… (Deuteronomy 31:6)",
  "He will cover you with His feathers… (Psalm 91:4)",
  "The Lord is near to all who call on Him… (Psalm 145:18)",
  "Faith, hope, and love… (1 Corinthians 13:13)",
  "Rejoice in hope, be patient in tribulation… (Romans 12:12)",
  "Cast your burden on the Lord… (Psalm 55:22)",
  "The Lord your God is with you… (Zephaniah 3:17)",
  "God will supply all your needs… (Philippians 4:19)",
  "Trust in the Lord forever… (Isaiah 26:4)",
  "I have loved you with an everlasting love… (Jeremiah 31:3)",
  "The Lord is faithful… (1 Corinthians 1:9)",
  "Serve the Lord with gladness… (Psalm 100:2)",
  "The Lord is righteous in all His ways… (Psalm 145:17)",
  "He restores my soul… (Psalm 23:3)",
  "Blessed are those who mourn… (Matthew 5:4)",
  "The Lord is my strength… (Psalm 28:7)",
  "Delight yourself in the Lord… (Psalm 37:4)",
  "The Lord is compassionate… (Psalm 103:8)",
  "He gives power to the faint… (Isaiah 40:29)",
  "The Lord is good to all… (Psalm 145:9)",
  "Be strong and take heart… (Psalm 31:24)",
  "Love one another as I have loved you… (John 15:12)",
  "The Lord is my refuge… (Psalm 46:1)",
  "Cast your cares on the Lord… (1 Peter 5:7)",
  "The Lord is my shepherd… (Psalm 23:1)",
  "God is our refuge… (Psalm 46:1)",
  "Let your light shine… (Matthew 5:16)",
  "Rejoice in the Lord… (Philippians 4:4)",
  "The Lord bless you and keep you… (Numbers 6:24-26)",
  "Be strong and courageous… (Joshua 1:9)",
  "Do not fear… (Isaiah 41:10)",
  "The Lord is near… (Psalm 145:18)",
  "Your word is a lamp… (Psalm 119:105)",
  "Faith can move mountains… (Matthew 17:20)",
  "Serve one another… (Galatians 5:13)",
  "Be kind and compassionate… (Ephesians 4:32)",
  "God is love… (1 John 4:8)",
  "The Lord will fight for you… (Exodus 14:14)",
  "Come to me all who are weary… (Matthew 11:28)",
  "Do not be anxious… (Philippians 4:6)",
  "The Lord is my rock… (Psalm 18:2)",
  "Blessed are the peacemakers… (Matthew 5:9)"
];
